#the maximum number of coingecko tokens is 6

wallets:
  ['Phantom', 'Keplr', 'Metamask', 'Sui', 'OKX', 'Total']
metrics:
  ['Portfolio value', 'Absolute ROI', 'PnL day', 'Rewards']

phantom:
  run_meteora: False
  ticker_coingecko: ['CWIF', 'IQ50', 'LST']


keplr:
  ticker_coingecko: ['STTIA']

metamask:
  ticker_coingecko: ['RSWETH']

trust:
  ticker_coingecko: []

okx:
  ticker_coingecko: ['WEETH']

solflare:






